<?php

return [
    'stores' => [
        [
            'id' => 1,
            'name' => 'Toko Roti Barokah',
            'category' => 'Bakery',
            'distance' => '0.5 km',
            'rating' => 4.8,
            'reviews' => 128,
            'address' => 'Jl. Sudirman No. 123, Jakarta',
            'tags' => ['halal', 'bakery'],
            'is_favorite' => true,
            'image' => 'https://images.unsplash.com/photo-1666114170628-b34b0dcc21aa?auto=format&fit=crop&q=80&w=1200',
            'deals' => [
                [
                    'id' => 1,
                    'item' => 'Roti Tawar',
                    'original_price' => 15000,
                    'discount_price' => 10000,
                    'stock' => 15,
                    'expires_in' => '2 jam',
                ],
                [
                    'id' => 2,
                    'item' => 'Roti Keju',
                    'original_price' => 12000,
                    'discount_price' => 8000,
                    'stock' => 20,
                    'expires_in' => '3 jam',
                ],
            ],
        ],
        [
            'id' => 2,
            'name' => 'Healthy Corner',
            'category' => 'Healthy Food',
            'distance' => '1.2 km',
            'rating' => 4.9,
            'reviews' => 95,
            'address' => 'Jl. Gatot Subroto No. 45, Jakarta',
            'tags' => ['vegan', 'healthy', 'halal'],
            'is_favorite' => true,
            'image' => 'https://images.unsplash.com/photo-1654458804670-2f4f26ab3154?auto=format&fit=crop&q=80&w=1200',
            'deals' => [
                [
                    'id' => 3,
                    'item' => 'Salad Bowl Premium',
                    'original_price' => 45000,
                    'discount_price' => 30000,
                    'stock' => 8,
                    'expires_in' => '3 jam',
                ],
                [
                    'id' => 4,
                    'item' => 'Smoothie Bowl',
                    'original_price' => 35000,
                    'discount_price' => 25000,
                    'stock' => 10,
                    'expires_in' => '4 jam',
                ],
            ],
        ],
        [
            'id' => 3,
            'name' => 'Dapur Nusantara',
            'category' => 'Indonesian Food',
            'distance' => '0.8 km',
            'rating' => 4.7,
            'reviews' => 156,
            'address' => 'Jl. Thamrin No. 78, Jakarta',
            'tags' => ['halal', 'indonesian'],
            'is_favorite' => false,
            'image' => 'https://images.unsplash.com/photo-1543352632-fea6d4f83e78?auto=format&fit=crop&q=80&w=1200',
            'deals' => [
                [
                    'id' => 5,
                    'item' => 'Lunch Box Komplit',
                    'original_price' => 50000,
                    'discount_price' => 35000,
                    'stock' => 12,
                    'expires_in' => '4 jam',
                ],
            ],
        ],
    ],
    'inventory_products' => [
        [
            'id' => 1,
            'name' => 'Roti Tawar',
            'category' => 'Bakery',
            'price' => 15000,
            'discount_price' => 10000,
            'stock' => 25,
            'expires_at' => '2026-04-14 18:00',
            'status' => 'flash-sale',
            'image' => 'https://images.unsplash.com/photo-1666114170628-b34b0dcc21aa?auto=format&fit=crop&q=80&w=1200',
            'description' => 'Roti tawar lembut dari batch pagi.',
        ],
        [
            'id' => 2,
            'name' => 'Salad Bowl',
            'category' => 'Healthy',
            'price' => 35000,
            'discount_price' => 25000,
            'stock' => 12,
            'expires_at' => '2026-04-14 15:00',
            'status' => 'flash-sale',
            'image' => 'https://images.unsplash.com/photo-1654458804670-2f4f26ab3154?auto=format&fit=crop&q=80&w=1200',
            'description' => 'Salad segar dengan dressing rendah kalori.',
        ],
        [
            'id' => 3,
            'name' => 'Lunch Box',
            'category' => 'Meal',
            'price' => 45000,
            'discount_price' => 30000,
            'stock' => 8,
            'expires_at' => '2026-04-14 20:00',
            'status' => 'flash-sale',
            'image' => 'https://images.unsplash.com/photo-1543352632-fea6d4f83e78?auto=format&fit=crop&q=80&w=1200',
            'description' => 'Lunch box komplit dengan lauk dan sayur.',
        ],
        [
            'id' => 4,
            'name' => 'Roti Keju',
            'category' => 'Bakery',
            'price' => 12000,
            'discount_price' => 0,
            'stock' => 30,
            'expires_at' => '2026-04-15 10:00',
            'status' => 'normal',
            'image' => 'https://images.unsplash.com/photo-1666114170628-b34b0dcc21aa?auto=format&fit=crop&q=80&w=1200',
            'description' => 'Roti keju gurih untuk snack sore.',
        ],
    ],
    'static_orders' => [
        [
            'id' => 'ORD-001',
            'customer' => ['name' => 'Budi Santoso', 'phone' => '08123456789', 'email' => 'budi@email.com'],
            'items' => [
                ['name' => 'Roti Tawar', 'quantity' => 3, 'price' => 10000],
                ['name' => 'Roti Keju', 'quantity' => 2, 'price' => 8000],
            ],
            'total' => 46000,
            'status' => 'pending',
            'pickup_code' => 'PICK-ABC123',
            'order_time' => '2026-04-14 09:30',
            'pickup_time' => '2026-04-14 17:00',
        ],
        [
            'id' => 'ORD-002',
            'customer' => ['name' => 'Siti Nurhaliza', 'phone' => '08198765432', 'email' => 'siti@email.com'],
            'items' => [
                ['name' => 'Salad Bowl', 'quantity' => 2, 'price' => 25000],
            ],
            'total' => 50000,
            'status' => 'pending',
            'pickup_code' => 'PICK-XYZ789',
            'order_time' => '2026-04-14 10:15',
            'pickup_time' => '2026-04-14 18:00',
        ],
    ],
    'transactions' => [
        [
            'id' => 'TRX-001',
            'order_id' => 'ORD-12345',
            'date' => '2026-04-10 18:30',
            'store' => 'Toko Roti Barokah',
            'store_address' => 'Jl. Sudirman No. 123, Jakarta',
            'items' => [
                ['name' => 'Roti Tawar', 'quantity' => 3, 'price' => 10000],
                ['name' => 'Roti Keju', 'quantity' => 2, 'price' => 8000],
            ],
            'subtotal' => 46000,
            'discount' => 16000,
            'total' => 30000,
            'status' => 'completed',
            'pickup_code' => 'PICK-ABC123',
            'rating' => 5,
            'review' => 'Roti masih fresh dan enak! Senang bisa membantu kurangi food waste.',
        ],
        [
            'id' => 'TRX-002',
            'order_id' => 'ORD-12346',
            'date' => '2026-04-09 12:15',
            'store' => 'Healthy Corner',
            'store_address' => 'Jl. Gatot Subroto No. 45, Jakarta',
            'items' => [
                ['name' => 'Salad Bowl Premium', 'quantity' => 2, 'price' => 30000],
            ],
            'subtotal' => 90000,
            'discount' => 30000,
            'total' => 60000,
            'status' => 'completed',
            'pickup_code' => 'PICK-XYZ789',
            'rating' => 5,
            'review' => 'Porsi besar dan sayuran masih segar!',
        ],
    ],
    'donations' => [
        [
            'id' => 'DON-001',
            'store' => ['name' => 'Toko Roti Barokah', 'address' => 'Jl. Sudirman No. 123, Jakarta', 'phone' => '021-12345678'],
            'items' => [
                ['name' => 'Roti Tawar', 'quantity' => 15],
                ['name' => 'Roti Keju', 'quantity' => 10],
            ],
            'distance' => '2.5 km',
            'available_until' => '2026-04-14 20:00',
            'status' => 'available',
            'claimed_at' => null,
            'tracking_status' => null,
            'delivered_at' => null,
        ],
        [
            'id' => 'DON-002',
            'store' => ['name' => 'Healthy Corner', 'address' => 'Jl. Gatot Subroto No. 45, Jakarta', 'phone' => '021-87654321'],
            'items' => [
                ['name' => 'Salad Bowl', 'quantity' => 8],
                ['name' => 'Sandwich', 'quantity' => 7],
            ],
            'distance' => '3.2 km',
            'available_until' => '2026-04-14 19:00',
            'status' => 'available',
            'claimed_at' => null,
            'tracking_status' => null,
            'delivered_at' => null,
        ],
        [
            'id' => 'DON-003',
            'store' => ['name' => 'Dapur Nusantara', 'address' => 'Jl. Thamrin No. 78, Jakarta', 'phone' => '021-11223344'],
            'items' => [
                ['name' => 'Lunch Box Komplit', 'quantity' => 20],
            ],
            'distance' => '1.8 km',
            'available_until' => '2026-04-14 21:00',
            'status' => 'claimed',
            'claimed_at' => '2026-04-14 14:30',
            'tracking_status' => 'in-transit',
            'delivered_at' => null,
        ],
        [
            'id' => 'DON-004',
            'store' => ['name' => 'Toko Roti Barokah', 'address' => 'Jl. Sudirman No. 123, Jakarta', 'phone' => '021-12345678'],
            'items' => [
                ['name' => 'Roti Tawar', 'quantity' => 30],
                ['name' => 'Croissant', 'quantity' => 15],
            ],
            'distance' => '2.5 km',
            'available_until' => '2026-04-13 18:00',
            'status' => 'completed',
            'claimed_at' => '2026-04-13 15:00',
            'tracking_status' => 'delivered',
            'delivered_at' => '2026-04-13 17:30',
        ],
    ],
    'applications' => [
        [
            'id' => 1,
            'name' => 'Toko Roti Sejahtera',
            'type' => 'mitra',
            'email' => 'roti.sejahtera@email.com',
            'phone' => '021-12345678',
            'address' => 'Jl. Sudirman No. 100, Jakarta Pusat',
            'submitted_at' => '2026-04-14 09:00',
            'documents' => ['SIUP', 'NIB', 'Sertifikat Halal'],
            'status' => 'pending',
            'business_type' => 'Bakery & Pastry',
            'description' => 'Toko roti dengan 3 cabang di Jakarta',
        ],
        [
            'id' => 2,
            'name' => 'Yayasan Harapan Bangsa',
            'type' => 'lembaga',
            'email' => 'yayasan.harapan@email.com',
            'phone' => '021-87654321',
            'address' => 'Jl. Gatot Subroto No. 45, Jakarta Selatan',
            'submitted_at' => '2026-04-14 08:30',
            'documents' => ['Akta Pendirian', 'SK Kemenkumham', 'NPWP Lembaga', 'Surat Domisili'],
            'status' => 'pending',
            'business_type' => 'Panti Asuhan',
            'description' => 'Yayasan panti asuhan dengan 80 anak asuh',
            'beneficiaries' => 80,
        ],
        [
            'id' => 3,
            'name' => 'Healthy Cafe',
            'type' => 'mitra',
            'email' => 'healthy.cafe@email.com',
            'phone' => '021-11223344',
            'address' => 'Jl. Thamrin No. 78, Jakarta Pusat',
            'submitted_at' => '2026-04-13 16:45',
            'documents' => ['SIUP', 'NIB', 'Sertifikat Halal'],
            'status' => 'pending',
            'business_type' => 'Healthy Food & Cafe',
            'description' => 'Cafe dengan menu healthy food dan organic',
        ],
    ],
    'users' => [
        ['id' => 1, 'name' => 'Budi Santoso', 'email' => 'budi@email.com', 'phone' => '08123456789', 'type' => 'consumer', 'status' => 'active', 'joined_at' => '2026-01-15', 'transactions' => 24, 'warnings' => 0],
        ['id' => 2, 'name' => 'Toko Roti Barokah', 'email' => 'roti.barokah@email.com', 'phone' => '021-12345678', 'type' => 'mitra', 'status' => 'active', 'joined_at' => '2026-01-10', 'transactions' => 156, 'warnings' => 0, 'verified' => true],
        ['id' => 3, 'name' => 'Yayasan Peduli Anak', 'email' => 'yayasan.peduli@email.com', 'phone' => '021-87654321', 'type' => 'lembaga', 'status' => 'active', 'joined_at' => '2026-02-01', 'transactions' => 45, 'warnings' => 0, 'verified' => true],
        ['id' => 4, 'name' => 'Siti Nurhaliza', 'email' => 'siti@email.com', 'phone' => '08198765432', 'type' => 'consumer', 'status' => 'active', 'joined_at' => '2026-02-20', 'transactions' => 12, 'warnings' => 0],
        ['id' => 5, 'name' => 'Healthy Corner', 'email' => 'healthy.corner@email.com', 'phone' => '021-11223344', 'type' => 'mitra', 'status' => 'active', 'joined_at' => '2026-01-25', 'transactions' => 98, 'warnings' => 0, 'verified' => true],
        ['id' => 6, 'name' => 'Ahmad Rizki', 'email' => 'ahmad@email.com', 'phone' => '08156781234', 'type' => 'consumer', 'status' => 'warned', 'joined_at' => '2026-03-01', 'transactions' => 8, 'warnings' => 2, 'last_warning' => '2026-04-12', 'warning_reason' => 'Tidak mengambil pesanan yang sudah dibooking (2x)'],
        ['id' => 7, 'name' => 'Toko ABC', 'email' => 'toko.abc@email.com', 'phone' => '021-99887766', 'type' => 'mitra', 'status' => 'blocked', 'joined_at' => '2026-02-15', 'transactions' => 32, 'warnings' => 3, 'blocked_at' => '2026-04-13', 'block_reason' => 'Menjual makanan yang sudah tidak layak konsumsi (pelanggaran berat)', 'verified' => true],
        ['id' => 8, 'name' => 'Ahmad Fathurrohman (Consumer)', 'email' => 'ahmad.fathurrohman26@gmail.com', 'password' => '123123', 'phone' => '081234567890', 'type' => 'consumer', 'status' => 'active', 'joined_at' => '2026-04-14', 'transactions' => 0, 'warnings' => 0],
        ['id' => 9, 'name' => 'Ahmad Fathurrohman (Mitra)', 'email' => 'ahmad.fathurrohman26@gmail.com', 'password' => '123123', 'phone' => '081234567891', 'type' => 'mitra', 'status' => 'active', 'joined_at' => '2026-04-14', 'transactions' => 0, 'warnings' => 0, 'verified' => true],
        ['id' => 10, 'name' => 'Ahmad Fathurrohman (Lembaga)', 'email' => 'ahmad.fathurrohman26@gmail.com', 'password' => '123123', 'phone' => '081234567892', 'type' => 'lembaga', 'status' => 'active', 'joined_at' => '2026-04-14', 'transactions' => 0, 'warnings' => 0, 'verified' => true],
        ['id' => 11, 'name' => 'Ahmad Fathurrohman (Admin)', 'email' => 'ahmad.fathurrohman26@gmail.com', 'password' => '123123', 'phone' => '081234567893', 'type' => 'admin', 'status' => 'active', 'joined_at' => '2026-04-14', 'transactions' => 0, 'warnings' => 0, 'verified' => true],
    ],
    'articles' => [
        [
            'id' => 1,
            'title' => '5 Cara Mengurangi Food Waste di Rumah',
            'category' => 'Tips',
            'status' => 'Published',
            'date' => '2026-03-25',
            'author' => 'Admin System',
            'content' => 'Langkah-langkah praktis untuk mengurangi food waste yang bisa dimulai dari dapur Anda sendiri.',
            'image' => 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800',
            'read_time' => '3 min read',
        ],
        [
            'id' => 2,
            'title' => 'Dampak Sampah Makanan Terhadap Perubahan Iklim',
            'category' => 'Artikel',
            'status' => 'Published',
            'date' => '2026-03-28',
            'author' => 'Admin System',
            'content' => 'Tahukah Anda bahwa sampah makanan berkontribusi besar terhadap gas rumah kaca? Berikut adalah faktanya.',
            'image' => 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
            'read_time' => '5 min read',
        ],
        [
            'id' => 3,
            'title' => 'Panduan Menyimpan Sayur dan Buah Agar Tahan Lama',
            'category' => 'Panduan',
            'status' => 'Published',
            'date' => '2026-03-30',
            'author' => 'Admin System',
            'content' => 'Pelajari trik menyimpan bahan makanan agar tetap segar berminggu-minggu.',
            'image' => 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800',
            'read_time' => '4 min read',
        ],
        [
            'id' => 4,
            'title' => 'Mengenal Perbedaan Best Before dan Expired Date',
            'category' => 'Edukasi',
            'status' => 'Published',
            'date' => '2026-04-01',
            'author' => 'Admin System',
            'content' => 'Pahami perbedaan kedua istilah ini agar tidak membuang makanan yang masih layak konsumsi.',
            'image' => 'https://images.unsplash.com/photo-1584473457406-6240486418e9?auto=format&fit=crop&q=80&w=800',
            'read_time' => '3 min read',
        ],
        [
            'id' => 5,
            'title' => 'Panduan Donasi Makanan Aman',
            'category' => 'Panduan',
            'status' => 'Draft',
            'date' => '2026-04-14',
            'author' => 'Admin System',
            'content' => 'Sebelum mendonasikan makanan, ada beberapa standar keamanan pangan yang perlu diperhatikan.',
            'image' => 'https://images.unsplash.com/photo-1593113702251-272b1bc414a9?auto=format&fit=crop&q=80&w=800',
            'read_time' => '4 min read',
        ],
    ],
];
